const express = require('express');
const router = express.Router();
const bcrypt = require('bcrypt');

const User = require('../../database/models/User');
const Provincia = require('../../database/models/Provincia');



// Show all provincias
router.get('/provincias', (req, res) => {
    Provincia.findAll({ include: { all: true } })
        .then(provincias => res.json(provincias))
        .catch(err => res.json(err));
});

// Auth
// Test login with HASH generated by PHP
router.post('/login', (req, res) => {
    
    let email = req.body.email;
    hash = hash.replace('$2y$', '$2b$');

    bcrypt.compare(req.body.password, hash, function(err, result) {

        res.send(result);
    });
    
});


module.exports = router;